### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by Tr3yb0** [codeforgso/website#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zenlex** [comment]
From Jordan via Trello:
Here is the list of leadership members thus far: (Will Update in the start of 2021.)

Tim Leisman
Schaffer Stweart
Rob Martin
Heather Gallop
Jordan Robinson
Ethan McElvaney
Tre Botard
Erich Keil
