### ISSUE TITLE
hello@codeforgreesnsboro.org dysfunctional

### ISSUE THREAD

**Issue by zenlex** [codeforgso/website#29]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tr3yb0** [comment]
Need to resolve forwarding to leadership team

**Comment by Tr3yb0** [comment]
Moved issue to Trello
