### ISSUE TITLE
Security Vulnerabilities - Dependencies Need Updating

### ISSUE THREAD

**Issue by zenlex** [codeforgso/website#33]
Need to run an npm audit and fix. 

I did a quick test pull and audit and I think all but one of the vulnerabilities have automatic fixes.

**Comment by Tr3yb0** [comment]
Last issue dependent on gatsby updating the references to their dependencies. 
[Gatsby Issue](https://github.com/gatsbyjs/gatsby/issues/26128) 

All of the rest have been updated and merged into main.

**Comment by zenlex** [comment]
This last issue looks like it's fixed with the latest gatsby patch I rolled into PR
